### ISSUE TITLE
Can't handle more than 2 gateways

### ISSUE THREAD

**Issue by alien2003** [SpectrumIM/spectrum2#361]
Hey! I have Spectrum 2 installed with Docker and ejabberd:
`docker run --name="spectrum2" -d --restart unless-stopped -v /opt/spectrum2/configuration:/etc/spectrum2/transports -v /opt/spectrum2/data:/var/lib/spectrum2 spectrum2/spectrum`

Discord, Telegram and Skype gateways configured:
```
[service]
allowed_servers=hostname
jid = skype.hostname
password = password
server = 172.17.0.1
port = 5347
backend_host = 127.0.0.1
users_per_backend=10
backend=/usr/bin/spectrum2_libpurple_backend
protocol=prpl-skypeweb
enable_remove_buddy=true

[identity]
name=Skype
type=xmpp

[logging]
config = /etc/spectrum2/logging.cfg
backend_config = /etc/spectrum2/backend-logging.cfg

[database]
type = sqlite3

[registration]
enable_public_registration=0
```
Port and protocol are different for all gateways.

The same configuration for other libpurple plugins.
Ejabberd configuration installed on host system outside of Docker:
```
  -
    port: 5347
    module: ejabberd_service
    access: all
    shaper_rule: fast
    ip: "172.17.0.1"
    hosts:
        "skype.hostname":
            password: "password"
  -
    port: 5348
    module: ejabberd_service
    access: all
    shaper_rule: fast
    ip: "172.17.0.1"
    hosts:
        "tg.hostname":
            password: "password"
  -
    port: 5350
    module: ejabberd_service
    access: all
    shaper_rule: fast
    ip: "172.17.0.1"
    hosts:
        "discord.hostname":
            password: "password"
```

Only 2 gateways can be up at any time. If I force start broken gateway with `docker exec spectrum2 spectrum2_manager discord.hostname restart` gateway starts but some of already started gateways goes down. When the gateway is down the output of `docker exec spectrum2 spectrum2_manager skype.hostname status` is `Can't connect the server`. XMPP client says `DNS lookup failed: non-existing domain` when I try to register on broken gateway.

All gateways are working but not more than two at once
