### ISSUE TITLE
Support for group invites

### ISSUE THREAD

**Issue by moyamo** [SpectrumIM/spectrum2#91]
As defined in [XEP-0045 (Mediated Invites)](http://xmpp.org/extensions/xep-0045.html#invite-mediated). With the protocol buffers I think we could reuse ConversationMessage and just have a different type (e.g. TYPE_ROOM_INVITE)
This could be translated to:

``` xml
<message
    from='coven@chat.shakespeare.lit'
    id='nzd143v8'
    to='hecate@shakespeare.lit'>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <invite from='crone1@shakespeare.lit/desktop'>
      <reason>
        Hey Hecate, this is the place for all good witches!
      </reason>
    </invite>
    <password>cauldronburn</password>
  </x>
</message>
```

``` yaml
ConversationMessage:
    userName: coven@chat.shakespeare.lit
    buddyName: hecate@shakespeare.lit
    nickname: crone1@shakespeare.lit
    message: Hey Hecate, this is the place for all good witches!
    timestamp: <timestamp>
    headline: cauldronburn
    id: nzd143v8

```
